# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# ZSH Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Oh-My-ZSH Plugins
plugins=(git brew zsh-autosuggestions zsh-syntax-highlighting)

# Source Oh-My-ZSH. This will also source any files in $ZSH_CUSTOM
source $ZSH/oh-my-zsh.sh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/martin/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/martin/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/martin/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/martin/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# THIS MUST BE THE LAST LINE TO ENSURE ALL ENV VARS ARE SET BEFORE P10K LOADS
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
