# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# ZSH Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Oh-My-ZSH Plugins (cross-platform)
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS with Homebrew
    plugins=(git brew zsh-autosuggestions zsh-syntax-highlighting)
else
    # Linux and other systems
    plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
fi

# Source Oh-My-ZSH. This will also source any files in $ZSH_CUSTOM
source $ZSH/oh-my-zsh.sh

# Basic cross-platform aliases that should work everywhere
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias la='ls -lah'
alias ll='ls -alh'
alias l='ls -lh'

# OS-specific configurations will be loaded via $ZSH_CUSTOM files

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# Cross-platform conda initialization
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS conda path
    __conda_setup="$('/Users/martin/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/Users/martin/opt/miniconda3/etc/profile.d/conda.sh" ]; then
            . "/Users/martin/opt/miniconda3/etc/profile.d/conda.sh"
        else
            export PATH="/Users/martin/opt/miniconda3/bin:$PATH"
        fi
    fi
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux conda paths (common locations)
    for conda_path in "$HOME/miniconda3" "$HOME/anaconda3" "/opt/miniconda3" "/opt/anaconda3" "$HOME/opt/miniconda3"; do
        if [ -f "$conda_path/bin/conda" ]; then
            __conda_setup="$('$conda_path/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
            if [ $? -eq 0 ]; then
                eval "$__conda_setup"
                break
            else
                if [ -f "$conda_path/etc/profile.d/conda.sh" ]; then
                    . "$conda_path/etc/profile.d/conda.sh"
                    break
                else
                    export PATH="$conda_path/bin:$PATH"
                    break
                fi
            fi
        fi
    done
fi
unset __conda_setup
# <<< conda initialize <<<

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# THIS MUST BE THE LAST LINE TO ENSURE ALL ENV VARS ARE SET BEFORE P10K LOADS
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
